import '@coinbase/onchainkit/styles.css'
import './globals.css'
import type { Metadata } from 'next'
import type { ReactNode } from 'react'

import { Inter } from 'next/font/google'
import { headers } from 'next/headers'
import { cookieToInitialState } from 'wagmi'

import { Providers } from '../providers'
import { config } from '../lib/wagmi'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Wagmi',
  description: 'Generated by create-wagmi',
}

export default async function RootLayout({ children }: { children: ReactNode }) {
  const initialState = cookieToInitialState(
    config,
    (await headers()).get('cookie')
  )

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers initialState={initialState}>{children}</Providers>
      </body>
    </html>
  )
}
